export const textChapters = {
	ENGKJV: [
		{
			book_id: 'GEN',
			book_id_usfx: 'GN',
			book_id_osis: 'Gen',
			name: 'Genesis',
			testament: 'OT',
			testament_order: 1,
			book_order: 1,
			book_group: 'The Law',
			chapters: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		},
		{
			book_id: 'EXO',
			book_id_usfx: 'EX',
			book_id_osis: 'Exod',
			name: 'Exodus',
			testament: 'OT',
			testament_order: 2,
			book_order: 2,
			book_group: 'The Law',
			chapters: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		},
		{
			book_id: 'MAT',
			book_id_usfx: 'MT',
			book_id_osis: 'Matt',
			name: 'Matthew',
			testament: 'NT',
			testament_order: 1,
			book_order: 41,
			book_group: 'Gospels',
			chapters: [11],
		},
		{
			book_id: 'MRK',
			book_id_usfx: 'MK',
			book_id_osis: 'Mark',
			name: 'Mark',
			testament: 'NT',
			testament_order: 2,
			book_order: 42,
			book_group: 'Gospels',
			chapters: [15],
		},
		{
			book_id: 'LUK',
			book_id_usfx: 'LK',
			book_id_osis: 'Luke',
			name: 'Luke',
			testament: 'NT',
			testament_order: 3,
			book_order: 43,
			book_group: 'Gospels',
			chapters: [7, 8, 9, 10],
		},
		{
			book_id: 'JHN',
			book_id_usfx: 'JN',
			book_id_osis: 'John',
			name: 'John',
			testament: 'NT',
			testament_order: 4,
			book_order: 44,
			book_group: 'Gospels',
			chapters: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		},
	],
};
export const audioChapters = {
	ENGKJVN2DA: [
		{
			book_id: 'MAT',
			book_id_usfx: 'MT',
			book_id_osis: 'Matt',
			name: 'Matthew',
			testament: 'NT',
			testament_order: 1,
			book_order: 41,
			book_group: 'Gospels',
			chapters: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		},
		{
			book_id: 'MRK',
			book_id_usfx: 'MK',
			book_id_osis: 'Mark',
			name: 'Mark',
			testament: 'NT',
			testament_order: 2,
			book_order: 42,
			book_group: 'Gospels',
			chapters: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		},
		{
			book_id: 'LUK',
			book_id_usfx: 'LK',
			book_id_osis: 'Luke',
			name: 'Luke',
			testament: 'NT',
			testament_order: 3,
			book_order: 43,
			book_group: 'Gospels',
			chapters: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		},
	],
};
