const paper = {
	'--background-color': '#FFF',
	'--text-selection-background': '#F8E4D3',
	'--text-selection-accordion-title-background': '#703F33',
	'--text-selection-accordion-body-background': '#F4F6F9',
	'--text-selection-tab-option-active-background': '#1B1F24',
	'--text-selection-tab-option-active-color': '#FFFFFF',
	'--text-selection-tab-option-active-border-color': '#1B1F24',
	'--book-dropdown-background-color': '#F8E4D3',
	'--book-dropdown-chapter-background-color': '#B2BBC6',
	'--book-dropdown-text-color': '#000000',
	'--book-dropdown-section-background-color': '#FFFFFF',
	'--main-textarea-svg-color': '#000000',
	'--main-textarea-svg-fill-color': '#000000',
	'--main-textarea-read-chapter-background': '#FFFFF5',
	'--main-textarea-read-chapter-shadow': '#B1A77A',
	'--main-textarea-read-chapter-active': '#B1A77A',
	'--active-color-primary': '#6FBC8F',
	'--active-color-secondary': '#71bc90',
	'--highlight-blue': '#387DBF',
	'--highlight-pink': '#D069A9',
	'--highlight-yellow': '#FCE600',
	'--highlight-green': '#2E924D',
	'--highlight-purple': '#8967AC',
	'--disabled-input-option': '#B2BBC6',
	'--inactive-font-option': '#868686',
	'--dark-theme-primary': '#000000',
	'--light-theme-primary': '#FDF9F3',
	'--default-theme-primary': '#7E0E2A',
	'--settings-text-color': '#FFFFFF',
	'--theme-option-border': '#B2BBC6',
	'--notebook-footer-background-color': '#1B1F24',
	'--notebook-title-date-color': '#6EC3E2',
	'--profile-forgot-password-color': '#6EC3E2',
	'--profile-login-signup-background-color': '#1B1F24',
	'--profile-invalid-input-background-color': '#9E1E35',
	'--context-menu-background-color': '#FFFFFF',
	'--context-menu-svg-fill-color': '#000000',
	'--context-menu-text-color': '#000000',
	'--context-menu-highlight-active-background-color': '#868686',
	'--audio-player-progress-bar-background': '#1B1F24',
	'--menu-body-background-color': '#2C3036',
	'--menu-header-background-color': '#7E0E2A',
	'--default-background-color': '#FDF9F3',
	'--default-header-background-color': '#FDF9F3',
	'--default-footer-background-color': '#FDF9F3',
	'--default-text-color': '#FFFFFF',
	'--before-after-border-color': '#999999',
	'--default-svg-fill-color': '#FFFFFF',
	'--default-input-placeholder-color': '#FFFFFF',
	'--application-text-super-color': '#000000',
	'--application-loading-spinner-color': '#aeaeae',
	'--default-header-background-color-transparent': '#F8E4D300',
	'--application-input-caret-color': '#000',
	'--application-text-caret-color': '#fff',
	'--application-transparent-gray': 'rgba(0,0,0,.8)',
	'--application-words-of-jesus': '#DA2015',
	'--application-text-selection-color': 'rgb(216, 182, 185)',
};

const dark = {
	'--text-selection-background': '#1B1F24',
	'--text-selection-accordion-title-background': '#2C3036',
	'--text-selection-accordion-body-background': '#1B1F24',
	'--text-selection-tab-option-active-background': '#FDF9F3',
	'--text-selection-tab-option-active-color': '#000000',
	'--text-selection-tab-option-active-border-color': '#FFFFFF',
	'--book-dropdown-background-color': '#F8E4D3',
	'--book-dropdown-chapter-background-color': '#FFFFFF',
	'--book-dropdown-text-color': '#000000',
	'--book-dropdown-section-background-color': '#6E747F',
	'--main-textarea-svg-color': '#000000',
	'--main-textarea-svg-fill-color': '#000000',
	'--main-textarea-read-chapter-background': '#FFFFF5',
	'--main-textarea-read-chapter-shadow': '#B1A77A',
	'--main-textarea-read-chapter-active': '#B1A77A',
	'--active-color-primary': '#6FBC8F',
	'--active-color-secondary': '#71bc90',
	'--highlight-blue': '#387DBF',
	'--highlight-pink': '#D069A9',
	'--highlight-yellow': '#FCE600',
	'--highlight-green': '#2E924D',
	'--highlight-purple': '#8967AC',
	'--disabled-input-option': '#B2BBC6',
	'--inactive-font-option': '#868686',
	'--dark-theme-primary': '#000000',
	'--light-theme-primary': '#FDF9F3',
	'--default-theme-primary': '#7E0E2A',
	'--settings-text-color': '#FFFFFF',
	'--notebook-footer-background-color': '#1B1F24',
	'--notebook-title-date-color': '#6EC3E2',
	'--profile-forgot-password-color': '#6EC3E2',
	'--profile-login-signup-background-color': '#1B1F24',
	'--profile-invalid-input-background-color': '#9E1E35',
	'--context-menu-background-color': '#FFFFFF',
	'--context-menu-svg-fill-color': '#000000',
	'--context-menu-text-color': '#000000',
	'--context-menu-highlight-active-background-color': '#868686',
	'--audio-player-progress-bar-background': '#1B1F24',
	'--menu-body-background-color': '#2C3036',
	'--menu-header-background-color': '#7E0E2A',
	'--default-background-color': '#000000',
	'--default-header-background-color': '#9E1E35',
	'--default-footer-background-color': '#9E1E35',
	'--default-text-color': '#FFFFFF',
	'--before-after-border-color': '#999999',
	'--default-svg-fill-color': '#FFFFFF',
	'--default-input-placeholder-color': '#FFFFFF',
	'--application-text-super-color': '#000000',
	'--application-loading-spinner-color': '#aeaeae',
	'--default-header-background-color-transparent': '#F8E4D300',
	'--application-input-caret-color': '#000',
	'--application-text-caret-color': '#fff',
	'--application-transparent-gray': 'rgba(0,0,0,.8)',
	'--application-words-of-jesus': '#DA2015',
	'--application-text-selection-color': 'rgb(216, 182, 185)',
};

const red = {
	'--text-selection-background': '#1B1F24',
	'--text-selection-accordion-title-background': '#2C3036',
	'--text-selection-accordion-body-background': '#1B1F24',
	'--text-selection-tab-option-active-background': '#FDF9F3',
	'--text-selection-tab-option-active-color': '#000000',
	'--text-selection-tab-option-active-border-color': '#FFFFFF',
	'--book-dropdown-background-color': '#F8E4D3',
	'--book-dropdown-chapter-background-color': '#FFFFFF',
	'--book-dropdown-text-color': '#000000',
	'--book-dropdown-section-background-color': '#6E747F',
	'--main-textarea-svg-color': '#000000',
	'--main-textarea-svg-fill-color': '#000000',
	'--main-textarea-read-chapter-background': '#FFFFF5',
	'--main-textarea-read-chapter-shadow': '#B1A77A',
	'--main-textarea-read-chapter-active': '#B1A77A',
	'--active-color-primary': '#6FBC8F',
	'--active-color-secondary': '#71bc90',
	'--highlight-blue': '#387DBF',
	'--highlight-pink': '#D069A9',
	'--highlight-yellow': '#FCE600',
	'--highlight-green': '#2E924D',
	'--highlight-purple': '#8967AC',
	'--disabled-input-option': '#B2BBC6',
	'--inactive-font-option': '#868686',
	'--dark-theme-primary': '#000000',
	'--light-theme-primary': '#FDF9F3',
	'--default-theme-primary': '#7E0E2A',
	'--settings-text-color': '#FFFFFF',
	'--theme-option-border': '#B2BBC6',
	'--notebook-footer-background-color': '#1B1F24',
	'--notebook-title-date-color': '#6EC3E2',
	'--profile-forgot-password-color': '#6EC3E2',
	'--profile-login-signup-background-color': '#1B1F24',
	'--profile-invalid-input-background-color': '#9E1E35',
	'--context-menu-background-color': '#FFFFFF',
	'--context-menu-svg-fill-color': '#000000',
	'--context-menu-text-color': '#000000',
	'--context-menu-highlight-active-background-color': '#868686',
	'--audio-player-progress-bar-background': '#1B1F24',
	'--menu-body-background-color': '#2C3036',
	'--menu-header-background-color': '#7E0E2A',
	'--default-background-color': '#FDF9F3',
	'--default-header-background-color': '#9E1E35',
	'--default-footer-background-color': '#9E1E35',
	'--default-text-color': '#FFFFFF',
	'--before-after-border-color': '#999999',
	'--default-svg-fill-color': '#FFFFFF',
	'--default-input-placeholder-color': '#FFFFFF',
	'--application-text-super-color': '#000000',
	'--application-loading-spinner-color': '#aeaeae',
	'--default-header-background-color-transparent': '#F8E4D300',
	'--application-input-caret-color': '#000',
	'--application-text-caret-color': '#fff',
	'--application-transparent-gray': 'rgba(0,0,0,.8)',
	'--application-words-of-jesus': '#DA2015',
	'--application-text-selection-color': 'rgb(216, 182, 185)',
};

const themes = {
	paper,
	dark,
	red,
};

const fonts = {
	sans: '"Noto Sans", Helvetica, sans serif',
	serif: '"Alegreya", "Palatino Linotype", Palatino, serif',
	slab: '"Roboto Slab", Rockwell, Courier, monospace',
};

const sizes = {
	0: '0.78em',
	18: '0.88em',
	42: '0.98em',
	69: '1.08em',
	100: '1.18em',
};

export const toggleWordsOfJesus = (state) => {
	document.documentElement.style.setProperty('--application-words-of-jesus', state ? '#A00' : 'inherit');
	sessionStorage.setItem('bible_is_words_of_jesus', state);
};

export const applyFontFamily = (fontFamily) => {
	document.documentElement.style.setProperty('--application-font-family', fonts[fontFamily]);
	sessionStorage.setItem('bible_is_font_family', fontFamily);
};

export const applyFontSize = (fontSize) => {
	document.documentElement.style.setProperty('--application-base-font-size', sizes[fontSize]);
	sessionStorage.setItem('bible_is_font_size', fontSize);
};

export const applyTheme = (theme) => {
	Object.entries(themes[theme]).forEach((property) => {
		document.documentElement.style.setProperty(property[0], property[1]);
	});
	sessionStorage.setItem('bible_is_theme', theme);
};
